### ISSUE TITLE
Webpush course refers to missing "TODO" in js/main.js

### ISSUE THREAD

**Issue by demianrenzulli** [google-developer-training/pwa-training-labs#37]
[Web Push course](https://developers.google.com/web/ilt/pwa/lab-integrating-web-push#36_optional_send_your_first_web_push_message_using_curl) refers to missing TODOs in the code of [js/main.js](https://github.com/google-developer-training/pwa-training-labs/blob/master/push-notification-lab/app/js/main.js): for example, 2.5, 2.6, 5.1.

These can be inferred by developers, but can also create some confusion on where to place the code snippets.

**Comment by DavidScales** [comment]
Hi @demianrenzulli, I just searched for the TODOs you listed in `main.js` and couldn't find them, but it looks like TODO 2.5 and 5.1 are actually added by the student in [TODO 2.4](https://developers.google.com/web/ilt/pwa/lab-integrating-web-push#24_add_notification_options) and TODO 2.6 is actually in the [`sw.js` file](https://github.com/google-developer-training/pwa-training-labs/blob/master/push-notification-lab/app/sw.js), which the instructions note. 

Does that clear up the potential confusion?

**Comment by demianrenzulli** [comment]
I think my main confusion came because I dodn't exactly followed the codelab copying the exact snippets of code, and skipped some steps. You're right about the comments, and also TODO 2.4, is also created by the student at 2.3.

Thank you!
