### ISSUE TITLE
cannot get started

### ISSUE THREAD

**Issue by jparish3** [google-developer-training/pwa-training-labs#43]
cd offline-quickstart-lab/app
npm install
node server.js
Error: Cannot find module '.../PWA/pwa-training-labs/server.js'
node -v
v11.10.0

**Comment by DavidScales** [comment]
> Error: Cannot find module '.../PWA/pwa-training-labs/server.js'

This means `node server.js` is looking in `.../PWA/pwa-training-labs/` for `server.js`, which implies your `cd offline-quickstart-lab/app` command was unsuccessful.

You just need to `cd` into the correct location (`.../PWA/pwa-training-labs/offline-quickstart-lab/app`)

If you feel unsure about how to navigate in the command line or don't know what "`cd`" does, check out some of these resources to learn more about it:
* [basic Windows commands](https://www.digitalcitizen.life/command-prompt-how-use-basic-commands)
* [navigating files and directories in unix](https://swcarpentry.github.io/shell-novice/02-filedir/index.html)
