### ISSUE TITLE
Gulp install for Course 4.1

### ISSUE THREAD

**Issue by GargoyleLizy** [google-developer-training/pwa-training-labs#46]
In Course 4.1, Step 6, Process Javascript
When we need to install the gulp-babel. 
The command is given as
npm install --save-dev gulp-babel babel-core babel-preset-env

But there is a warning given when installing
"gulp-babel@8.0.0 requires a peer of @babel/core@^7.0.0 but none is installed. You must install peer dependencies yourself. "
And this would prevent our "gulp processJs" work. 
We would get error: "Error: Cannot find module '@babel/core'"

In order to fix the error, we need to install the babel-core and babel-preset-env as peer dependencies with the command: 
npm install --save-dev @babel/core

Corresponding issue in [Gulp-Babel](https://github.com/babel/gulp-babel/issues/124)

**Comment by DavidScales** [comment]
should be fixed by #62
