### ISSUE TITLE
Incorrect file name in lab explanation

### ISSUE THREAD

**Issue by IvanBila** [google-developer-training/pwa-training-labs#55]
### Summary
In the [offline quickstart lab](https://codelabs.developers.google.com/codelabs/pwa-offline-quickstart/index.html?index=..%2F..dev-pwa-training#3) it is mentioned that the file that contains all the service worker code is named `sw.js` when the file is named [`service-worker.js`](https://github.com/google-developer-training/pwa-training-labs/blob/master/offline-quickstart-lab/app/service-worker.js). Is there a repo where I can make a PR to update it? @samdutton @DavidScales.

### Screenshots

![Screenshot from 2019-08-11 15-10-21](https://user-images.githubusercontent.com/13482373/62834277-338d2280-bc4a-11e9-929a-4ae62d1162a5.png)

**Comment by samdutton** [comment]
Thanks for the heads-up! I'll get this fixed.

**Comment by IvanBila** [comment]
This issue has been addressed, Thanks

![Screenshot from 2019-08-14 17-28-45](https://user-images.githubusercontent.com/13482373/63034126-06927700-beb9-11e9-991e-c5447c37aae3.png)
