### ISSUE TITLE
Problem getting started with indexeddb codelab

### ISSUE THREAD

**Issue by anushagadepalli** [google-developer-training/pwa-training-labs#57]
After running the server, when I open the browser I have the following error.

![Untitled](https://user-images.githubusercontent.com/14006059/63216874-fe248100-c0f0-11e9-83db-2bc7b994de4f.png)

**Comment by DavidScales** [comment]
Hi, sorry you're having trouble. Do you have any more information? Perhaps you could share the commands you are running and/or your command line output? Or what step you're on and if you've made code changes

**Comment by anushagadepalli** [comment]
Hello @DavidScales, thank you for the response.

- I will attach the screenshots of the commands I am running and command line output. 
- I am at step 2 `Get Set Up`. I did not change any code.

![1](https://user-images.githubusercontent.com/14006059/63311920-9454d480-c2b4-11e9-90d3-aff9a510b1d0.png)
![2](https://user-images.githubusercontent.com/14006059/63311921-9454d480-c2b4-11e9-9ff0-7e2f9a6ad0c8.png)

**Comment by DavidScales** [comment]
Thanks @anushagadepalli, I'm not able to reproduce the issue. But it looks like from your command logs that the server installs and runs successfully, and you are in the correct directory. So the issue could be on the browser end. 

Can you try starting the server again, and this time open localhost in an incognito window (or private window). If you're using Chrome, try clearing the caches and uninstalling previous service workers (Dev Tools > **Application** tab > **Clear storage** panel > **Clear site data** button) and then refreshing. 

Often when I am working with service workers on localhost, old service workers from previous work remain in the browser and can mess up requests. Let me know if that fixes it.

**Comment by anushagadepalli** [comment]
Hello @DavidScales, thank you for your suggestion. I found the issue. 
The application is available on `http://127.0.0.1:8080/index.html` as opposed to `http://127.0.0.1:8080`. Some background on my dev environment: I use a Windows OS, so may be the server cannot serve the app or could not access index.html? Any leads would be helpful. Thank you in advance.

**Comment by DavidScales** [comment]
Oh I see. I'm not sure why that is happening. But it's fine to use `http://127.0.0.1:8080/index.html`. Ideally `http://127.0.0.1:8080`, `http://127.0.0.1:8080/`, and `http://127.0.0.1:8080/index.html` should be requested the same from your browser, and should be returned the same from a server. But you're fine to continue the labs using whichever works on your system. Let me know if you have more questions! Best of luck
