### ISSUE TITLE
QUnit Test Error

### ISSUE THREAD

**Issue by cdaccarett93** [google-developer-training/pwa-training-labs#6]
Working with IndexedDB lab:

Uncaught TypeError: indexedDB.webkitGetDatabaseNames is not a function
  Source: /indexed-db-lab/app/test/test.html:48

`    function checkDb() {
      var dbExists = false;
      // Webkit only works in Chrome
      return promisifyRequest(indexedDB.webkitGetDatabaseNames())`

indexedDB.webkitGetDatabaseNames() is a deprecated feature
https://www.chromestatus.com/features/5725741740195840

**Comment by nasearle** [comment]
Thanks for bringing this up, Carlos! We'll look into it.

**Comment by satyakresna** [comment]
I got the same issue

**Comment by nasearle** [comment]
This should be fixed now. Thanks for the feedback!
