### ISSUE TITLE
Serve files from the cache - Wrong link caches.match  

### ISSUE THREAD

**Issue by Titoine** [google-developer-training/pwa-training-labs#69]
In the tutorial _Web Apps 05.0: Caching files with the service worker_, at the page [4. Serve files from the cache](https://codelabs.developers.google.com/codelabs/pwa-caching-service-worker/#3), you have two links caches.match that point to the [cache.match](https://developer.mozilla.org/en-US/docs/Web/API/Cache/match) and not to the[ cache**S**.match](https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage/match) documentation.

**Comment by DavidScales** [comment]
Thanks @Titoine! I've corrected the links
