### ISSUE TITLE
Issue in IndexedDB course

### ISSUE THREAD

**Issue by satyakresna** [google-developer-training/pwa-training-labs#7]
In section **3.3 Add objects to the object store**, when I press the ```Add products``` button, the items didn't save in the ```IndexedDB``` and comes error in my console like picture below.
![image](https://user-images.githubusercontent.com/11099186/30777263-3ae726b2-a0e9-11e7-8c85-e983ec8718b2.png)

In ``` IndexedDB > couches-n-things > products```:
![empty products](https://user-images.githubusercontent.com/11099186/30777280-d543e812-a0e9-11e7-99a8-4004a9069e51.PNG)

I hope this issue can be solved ASAP. Thanks a lot team.

**Comment by samdutton** [comment]
@nasearle fyi

**Comment by satyakresna** [comment]
I cannot continue the IndexedDB course fyi.

**Comment by nasearle** [comment]
Hi Satya, hmm that's a new one. I re-tested the lab and I'm not getting that error. Looks like you might have missed defining a primary key somewhere. Make sure you've got that keyPath defined correctly in this line in your main.js:

```
upgradeDb.createObjectStore('products', {keyPath: 'id'});
```

Also, once you've got everything working and there are no errors in the console, you might need to refresh IndexedDB in DevTools to be able to see your changes (right click IndexedDB and click Refresh IndexedDB). DevTools doesn't always accurately show what's in the database.

**Comment by satyakresna** [comment]
Hi @nasearle , thanks for your feedback. You're right! I do a typo in ```keypath```. So, I my previous code
```
 upgradeDb.createObjectStore('products', {keypath: 'id'});
```
**Correct code**
```
 upgradeDb.createObjectStore('products', {keyPath: 'id'});
```
May be I'm tired when I try this codelabs. Thanks a lot. I will close this issue.
