### ISSUE TITLE
Chapter 2 - Offline Quickstart - Gitbooks link leads to a 404

### ISSUE THREAD

**Issue by FelixGeelhaar** [google-developer-training/pwa-training-labs#81]
In the first README file the link to the gitbook leads to a 404 page: 
[Gitbook](https://google-developer-training.gitbooks.io/progressive-web-apps-ilt-codelabs/content/docs/lab_offline_quickstart.html)

**Comment by DavidScales** [comment]
thanks for pointing this out! The links should be removed in #84
