### ISSUE TITLE
Chapter 3 (Scripting the service worker) Still References test/ Directory

### ISSUE THREAD

**Issue by JoshuaBaunach** [google-developer-training/pwa-training-labs#83]
[In Section 2 (Get Set Up) of Chapter 3 (Scripting the service worker)](https://codelabs.developers.google.com/codelabs/pwa-scripting-the-service-worker/#1), the tutorial mentions the following:

> `test/` folder contains files for testing your progress

The `test/` folder was removed in #26. This is a minor issue, but it may cause confusion.

**Comment by DavidScales** [comment]
thanks for pointing that out! the reference should be removed now
