### ISSUE TITLE
#Question: Send hits from the service worker

### ISSUE THREAD

**Issue by satyakresna** [google-developer-training/pwa-training-labs#9]
Hi, I just in codelab : Integrating Analytics in the section *8. Using analytics in the service worker*. In this section the student can try experiment with push notification. Here's is the detail

[Test service worker](https://www.dropbox.com/s/0ixa5j7e6m5wj8j/Test%20google%20analytics%20in%20service%20worker.PNG?dl=0)

But, I didn't see the action or button to test push notification in google analytics lab page
[No push notification button in google analytics page](https://www.dropbox.com/s/3eev8vqo256xj4s/no%20push%20notification%20button%20in%20google%20analytics.png?dl=0)

Thanks.

**Comment by DavidScales** [comment]
Hi @satyakresna 

The lab app itself does not have a push notification feature. Rather, Chrome's Developer Tools allows you to test push notifications. Here are some instructions for [sending simulated push notifications with Chrome](https://google-developer-training.gitbooks.io/progressive-web-apps-ilt-codelabs/content/docs/tools_for_pwa_developers.html#push). I believe these instructions are linked early on in the lab, but I will add them in to section 8 as well for clarity.

You can also learn more about [debugging PWA's & service workers in Chrome developer tools](https://developers.google.com/web/tools/chrome-devtools/progressive-web-apps).

Thanks for the feedback!
